import React, { useState } from 'react';
import { Search, ChevronDown, ChevronUp, BookOpen, Lightbulb, Leaf, HelpCircle, FileText } from 'lucide-react';

const Education = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeFaq, setActiveFaq] = useState(null);

  const articles = [
    {
      id: 1,
      title: 'Climate Change 101: Understanding the Crisis',
      tag: 'Science',
      summary: 'A look into global temperature shifts, historical context, and the greenhouse effect driving our planet\'s warming trends.',
      icon: Leaf,
      readTime: '5 min read',
      content: 'Climate change refers to long-term shifts in temperatures and weather patterns. These shifts may be natural, but since the 1800s, human activities have been the main driver of climate change, primarily due to burning fossil fuels like coal, oil, and gas. Burning fossil fuels generates greenhouse gas emissions that act like a blanket wrapped around the Earth, trapping the sun’s heat and raising temperatures.'
    },
    {
      id: 2,
      title: 'Demystifying Greenhouse Gases (GHG)',
      tag: 'Environment',
      summary: 'Learn about CO2, Methane, Nitrous Oxide, and Fluorinated gases — how they are generated and their heat-trapping capacities.',
      icon: BookOpen,
      readTime: '6 min read',
      content: 'Greenhouse gases trap heat in the atmosphere, making the planet warmer. Carbon dioxide (CO2) is released through respiration, volcano eruptions, deforestation, and burning fossil fuels. Methane (CH4) is a hydrocarbon gas produced through livestock agriculture and the decomposition of waste in landfills. Nitrous oxide (N2O) is produced by soil cultivation, and fluorinated gases are synthetic, powerful gases emitted from industrial processes.'
    },
    {
      id: 3,
      title: 'Renewable Energy: Wind, Solar, and Hydro',
      tag: 'Technology',
      summary: 'Transitioning from coal and fossil systems to clean energy grids. Discover solar photovoltaic technology and wind turbine mechanics.',
      icon: Lightbulb,
      readTime: '8 min read',
      content: 'Renewable energy comes from natural sources that are constantly replenished, such as sunlight and wind. Solar energy is captured using photovoltaic cells that convert light directly to electricity. Wind power utilizes massive turbines driven by airflow to generate kinetic energy. Hydropower uses water flow in dams to spin electrical generators. Moving to these sources decreases global carbon footprints drastically.'
    },
    {
      id: 4,
      title: 'Sustainable Living: A Checklist for Households',
      tag: 'Lifestyle',
      summary: 'Simple steps to make your lifestyle eco-friendly, covering home insulation, thermal savings, shopping smart, and organic composting.',
      icon: FileText,
      readTime: '4 min read',
      content: 'Sustainable living is a lifestyle that attempts to reduce an individual\'s or society\'s use of the Earth\'s natural resources. You can reduce waste by composting, buying local, switching off phantom loads, air-drying clothes, reducing hot water cycles, and replacing single-passenger commuting with micro-mobility (bicycles) or public transit options.'
    }
  ];

  const faqs = [
    {
      question: 'What is a Carbon Footprint?',
      answer: 'A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. It is usually measured in metric tons or kilograms of CO2 equivalent per year.'
    },
    {
      question: 'How does going vegetarian reduce emissions?',
      answer: 'Raising livestock accounts for nearly 14.5% of global greenhouse emissions. Ruminants like cows produce large amounts of methane during digestion. Furthermore, growing animal feed requires massive land clearing (deforestation). Eating plant-based meals cuts down this demand and decreases carbon output up to 60%.'
    },
    {
      question: 'What is the average carbon footprint?',
      answer: 'The average carbon footprint for a person in the United States is about 16 tons (16,000 kg) per year, one of the highest rates in the world. Globally, the average is closer to 4 tons (4,000 kg). To avoid global temperature increases, the global target footprint per year needs to drop under 2,000 kg.'
    },
    {
      question: 'What is a "phantom load" in energy saving?',
      answer: 'Phantom load (or standby power) is the electricity consumed by electronic devices while they are switched off or on standby, but still plugged in. Appliances like TVs, chargers, and microwaves drain power 24/7, representing up to 10% of standard home electricity bills.'
    }
  ];

  const filteredArticles = articles.filter(art => 
    art.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
    art.tag.toLowerCase().includes(searchQuery.toLowerCase()) ||
    art.summary.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const toggleFaq = (index) => {
    if (activeFaq === index) {
      setActiveFaq(null);
    } else {
      setActiveFaq(index);
    }
  };

  return (
    <div className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-12 animate-slide-up">
      
      {/* Search Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
        <div>
          <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white">Educational Resources</h1>
          <p className="text-sm text-slate-500 dark:text-slate-400">
            Learn about climate science, green engineering, and practical shifts to scale down your footprint.
          </p>
        </div>
        <div className="relative w-full md:w-80">
          <Search className="absolute left-3.5 top-3 h-4.5 w-4.5 text-slate-400" />
          <input
            type="text"
            placeholder="Search articles or topics..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-11 pr-4 py-2 rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 focus:outline-none focus:ring-1 focus:ring-eco-500 text-sm text-slate-800 dark:text-slate-100"
          />
        </div>
      </div>

      {/* Articles Grid */}
      <div className="space-y-6">
        <h3 className="font-bold text-slate-800 dark:text-white text-lg border-b border-slate-100 dark:border-slate-800 pb-3">
          Articles & Infographics
        </h3>

        {filteredArticles.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {filteredArticles.map((art) => {
              const Icon = art.icon;
              return (
                <div 
                  key={art.id}
                  className="rounded-2xl bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 p-6 shadow-sm flex flex-col justify-between hover:shadow-md transition-shadow group"
                >
                  <div className="space-y-4">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] bg-eco-50 dark:bg-eco-950/40 border border-eco-200 dark:border-eco-900 text-eco-700 dark:text-eco-400 px-2.5 py-0.5 rounded-full font-bold uppercase">
                        {art.tag}
                      </span>
                      <span className="text-xs text-slate-400 dark:text-slate-500">{art.readTime}</span>
                    </div>

                    <h4 className="text-lg font-bold text-slate-900 dark:text-white group-hover:text-eco-600 dark:group-hover:text-eco-400 transition-colors">
                      {art.title}
                    </h4>
                    
                    <p className="text-sm text-slate-500 dark:text-slate-400 leading-relaxed">
                      {art.summary}
                    </p>
                  </div>

                  <div className="border-t border-slate-55 dark:border-slate-850/60 pt-4 mt-6">
                    <p className="text-xs text-slate-650 dark:text-slate-350 leading-relaxed italic">
                      {art.content}
                    </p>
                  </div>
                </div>
              );
            })}
          </div>
        ) : (
          <div className="text-center py-12 text-slate-400">
            No articles found matching "{searchQuery}". Try using other terms like "diet", "energy", or "waste".
          </div>
        )}
      </div>

      {/* FAQ Accordion Section */}
      <div className="space-y-6">
        <h3 className="font-bold text-slate-800 dark:text-white text-lg border-b border-slate-100 dark:border-slate-800 pb-3 flex items-center gap-2">
          <HelpCircle className="h-5 w-5 text-eco-600" />
          Frequently Asked Questions
        </h3>

        <div className="rounded-2xl border border-slate-150 dark:border-slate-800 divide-y divide-slate-150 dark:divide-slate-800 overflow-hidden bg-white dark:bg-slate-900 shadow-sm">
          {faqs.map((faq, idx) => {
            const isOpen = activeFaq === idx;
            return (
              <div key={idx} className="transition-all">
                <button
                  onClick={() => toggleFaq(idx)}
                  className="w-full flex items-center justify-between p-5 text-left font-bold text-sm sm:text-base text-slate-800 dark:text-white hover:bg-slate-50 dark:hover:bg-slate-850 transition-colors"
                >
                  <span>{faq.question}</span>
                  {isOpen ? <ChevronUp className="h-4.5 w-4.5 text-slate-400" /> : <ChevronDown className="h-4.5 w-4.5 text-slate-400" />}
                </button>
                {isOpen && (
                  <div className="p-5 bg-slate-50 dark:bg-slate-950/40 text-xs sm:text-sm text-slate-600 dark:text-slate-300 leading-relaxed animate-slide-up">
                    {faq.answer}
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

    </div>
  );
};

export default Education;
